baseURL = "https://bborm.org/"
languageCode = "en-us"
title = "Bethel Baptist Church of Rocky Mount"
theme = "alpha-church"
# themesDir = "../.."

rssLimit = 5
paginate = 4

enableEmoji = true

customCSS = "example.css"

[permalinks]
  sermons = "/sermons/:year/:month/:title/"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-2326736-20"

[taxonomies]
  tag = "tags"
  preacher = "preachers"
  series = "series"

#This theme can generate a multi-level menu.
#Use weight= to specify the order of menu items, and parent= to create a submenu item.
[menu]
  # [[menu.main]]
  #   name = "Home"
  #   url = "/"
  #   weight = 1

  [[menu.main]]
    name = "Sermons"
    url = "https://anchor.fm/bborm"
    weight = 1

  [[menu.main]]
    name = "Calendar"
    url = "/calendar"
    weight = 2

  [[menu.main]]
    name = "Our Pastor"
    url = "/kenny-heinzel"
    weight = 3

  [[menu.main]]
    name = "Contact"
    url = "/#call-to-action"
    weight = 4

  [[menu.main]]
    name = "Resources"
    url = "#"
    weight = 5

  [[menu.main]]
    name = "Beliefs"
    parent = "Resources"
    url = "/beliefs"
    weight = 1

    [[menu.main]]
    name = "Church History"
    parent = "Resources"
    url = "/church-history"
    weight = 2

    

    # [[menu.main]]
    # name = "Leaders"
    # parent = "Resources"
    # url = "/leaders"
    # weight = 4
  
    [[menu.main]]
    name = "Facebook"
    url = "https://www.facebook.com/BethelBaptistChurchOfRockyMount/"
    weight = 6

    [[menu.main]]
    name = "Giving"
    url = "/giving"
    weight = 10
# Paramaters for the whole site
[params]
  title = "Bethel Baptist Church of Rocky Mount"
  subtitle = ""
  author = "Clint Davis"
  languageCode = "en" #For Accessibility
  customCSS = ["example.css"]

  bible_popups = "faithlife" #faithlife, blb
  bible_version = "NKJV" #HCSB, NIV, NLT, ESV, etc.
  instant_page = false
  enable_giving = true
  [params.podcast]
    title = "Listen to Alpha Church"
    subtitle = ""
    summary = "Alpha-Church sermons, talks, messages—podcasted."
    email = "test@example.com"
    copyright = "Podcast: [CC0 (public domain)](//creativecommons.org/publicdomain/zero/1.0/)"
    image = "img/podcast-cover.jpg"
    category = "Religion & Spirituality"
    sub_category = "Christianity"
    anchorfm = "https://anchor.fm/bborm"

  [params.map]
    service = "osm" #"osm" for OpenStreetMaps or "google"
    # For Open Street Map widgets
    latitude = "33.1723"
    longitude = "-84.68269"
    zoom = "18"
    # If you want to use google maps you'll need an API Key from Google https://developers.google.com/maps/documentation/embed/get-api-key
    #service = "google"
    #api_key = "xxx"
    #language = "fr" #Optional
    #region = "FR" #Optional

  [params.contact]
    #Use this section to automate contact form.
    #Set service to either "netlify" or "formspree"
    #For formspree, please setup an account at https://formspree.io/
    #For netlify, please read https://www.netlify.com/docs/form-handling/
    #
    #If you use netlify, you'll need to set the confirm_page value (or elase users will see a generic netlify response)
    #If you use formspree, you'll need to set your formspree email address.
    service = "netlify"
    confirm_page = "/contact-thanks"
    # formspree_email=""


    [params.footer]
      copyright = [
                   "Design: [HTML5 UP](//html5up.net/alpha)",
                   "[Hugo Port](//gohugo.io) by [Daniel Saunders](//github.com/funkydan2)"
                  ]

    # [[params.links]]
    #   service = "Twitter"
    #   icon = "fa-twitter"
    #   icon_pack = "fab"
    #   link = "//twitter.com/"

    [[params.links]]
      service = "Facebook"
      icon = "fa-facebook"
      icon_pack = "fab"
      link = "https://www.facebook.com/BethelBaptistChurchOfRockyMount/"

    [[params.links]]
      service = "Podcast"
      icon = "fa-podcast"
      icon_pack = "fas"
      link = "https://anchor.fm/bborm"

    # [[params.links]]
    #   service = "Full RSS Feed"
    #   icon = "fa-rss"
    #   icon_pack = "fas"
    #   link = "/index.xml"
