baseURL = "https://bborm.org/"
languageCode = "en-us"
title = "Bethel Baptist Church of Rocky Mount"
theme = ['alpha-church']
# themesDir = "../.."

rssLimit = 5
paginate = 4

enableEmoji = true

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[taxonomies]
  tag = "tags"
  preacher = "preachers"
  series = "series"

#This theme can generate a multi-level menu.
#Use weight= to specify the order of menu items, and parent= to create a submenu item.
[menu]
  # [[menu.main]]
  #   name = "Home"
  #   url = "/"
  #   weight = 1

  [[menu.main]]
    name = "Sermons"
    url = "https://anchor.fm/bborm"
    weight = 1

  [[menu.main]]
    name = "Calendar"
    url = "/calendar"
    weight = 2

  [[menu.main]]
    name = "Our Pastor"
    url = "/kenny-heinzel"
    weight = 3

  [[menu.main]]
    name = "Contact"
    url = "/#call-to-action"
    weight = 4

  [[menu.main]]
    name = "Resources"
    url = "#"
    weight = 5

  [[menu.main]]
    name = "Beliefs"
    parent = "Resources"
    url = "/beliefs"
    weight = 1

    [[menu.main]]
    name = "Church History"
    parent = "Resources"
    url = "/church-history"
    weight = 2

    # [[menu.main]]
    # name = "Giving"
    # parent = "Resources"
    # url = "https://tithe.ly/give?c=758647"
    # weight = 3

    # [[menu.main]]
    # name = "Leaders"
    # parent = "Resources"
    # url = "/leaders"
    # weight = 4
  
    [[menu.main]]
    name = "Facebook"
    url = "https://www.facebook.com/BethelBaptistChurchOfRockyMount/"
    weight = 6

# Paramaters for the whole site
[params]
  title = "Bethel Baptist Church of Rocky Mount"
  subtitle = ""
  author = "Daniel Saunders"

  customCSS = ["example.css"]

  bible_popups = "faithlife" #faithlife, blb
  bible_version = "NKJV" #HCSB, NIV, NLT, ESV, etc.
  instant_page = true

  [params.podcast]
    title = "Listen to Alpha Church"
    subtitle = ""
    summary = "Alpha-Church sermons, talks, messages—podcasted."
    email = "test@example.com"
    copyright = "Podcast: [CC0 (public domain)](//creativecommons.org/publicdomain/zero/1.0/)"
    image = "img/podcast-cover.jpg"
    category = "Religion & Spirituality"
    sub_category = "Christianity"
    iTunes = "https://itunes.apple.com/us/podcast/tgc-word-of-the-week/id1034013280"
    feed = "https://www.thegospelcoalition.org/podcasts/word-of-the-week/feed/?feed=podcast"

  [params.map]
    service = "osm" #"osm" for OpenStreetMaps or "google"
    # For Open Street Map widgets
    latitude = "33.1723"
    longitude = "-84.68269"
    zoom = "18"
    # If you want to use google maps you'll need an API Key from Google https://developers.google.com/maps/documentation/embed/get-api-key
    #service = "google"
    #api_key = "XXXXXXXX"
    #language = "fr" #Optional
    #region = "FR" #Optional

  [params.contact]
    #Use this section to automate contact form.
    #Set service to either "netlify" or "formspree"
    #For formspree, please setup an account at https://formspree.io/
    #For netlify, please read https://www.netlify.com/docs/form-handling/
    #
    #If you use netlify, you'll need to set the confirm_page value (or elase users will see a generic netlify response)
    #If you use formspree, you'll need to set your formspree email address.
    service = "netlify"
    confirm_page = "/contact-thanks"
    # formspree_email=""

  #Paramaters for the home/landing page
  [params.landing]

    [params.landing.banner]
      image = "img/banner.jpg"

      [[params.landing.banner.button]]
        url = "#call-to-action"
        text = "Get in touch"
        type = "primary"

        # [[params.landing.banner.button]]
        # url = "#feature-icons"
        # text = "Find out more"

    #Details for the box below the banner
    [params.landing.services]
      title = "Church on Sunday"
      text = "We meet at 11 am at [160 Bethel Church Road, Luthersville GA 30251](https://www.openstreetmap.org/#map=18/33.17182/-84.68219)."
      map_location = "Bethel Baptist Church of Rocky Mount"

    [params.landing.feature_icons]
      #These feature icons look best if there's an even number of them.
      enable = false

      #Accent is a colour defined in the CSS file. Choose between 1 and 5
      [[params.landing.feature_icons.tile]]
        icon = "fa-hands-helping"
        icon_pack = "fas"
        accent = "1"
        title = "Serving"
        text = "Serving our community and spreading the love of Christ."

      [[params.landing.feature_icons.tile]]
        icon = "fa-church"
        icon_pack = "fas"
        accent = "2"
        title = "Meeting"
        text = "Meeting together to hear and study the Word."

      [[params.landing.feature_icons.tile]]
        icon = "fa-comments"
        icon_pack = "fas"
        accent = "5"
        title = "Speaking"
        text = "Proclaiming the Word of God to the world."

      [[params.landing.feature_icons.tile]]
        icon = "fa-heartbeat"
        icon_pack = "fas"
        accent = "3"
        title = "Loving"
        text = "Loving God and loving our neighbors."

    [params.landing.feature_images]
      #These feature images look best if there's an even number of them.
      enable = false

      [[params.landing.feature_images.tile]]
        image = "img/kids.jpg"
        title = "Childrens' Ministry"
        text = "A church for the family."
        url = "/kids"
        button_text = "Learn more"

      [[params.landing.feature_images.tile]]
        image = "img/midweek.jpg"
        title = "Midweek Ministries"
        text = "Want more during the week?"
        url = "#"
        button_text="Join a group today!"

    [params.landing.CTA]
      heading = "Get in touch!"
      message = "We'd love to hear from you."

    [params.footer]
      copyright = [
                   "Design: [HTML5 UP](//html5up.net/alpha)",
                   "[Hugo Port](//gohugo.io) by [Daniel Saunders](//github.com/funkydan2)"
                  ]

    # [[params.links]]
    #   service = "Twitter"
    #   icon = "fa-twitter"
    #   icon_pack = "fab"
    #   link = "//twitter.com/"

    [[params.links]]
      service = "Facebook"
      icon = "fa-facebook"
      icon_pack = "fab"
      link = "https://www.facebook.com/BethelBaptistChurchOfRockyMount/"

    [[params.links]]
      service = "Podcast"
      icon = "fa-podcast"
      icon_pack = "fas"
      link = "https://anchor.fm/bborm"

    # [[params.links]]
    #   service = "Full RSS Feed"
    #   icon = "fa-rss"
    #   icon_pack = "fas"
    #   link = "/index.xml"
