[context.production.environment]
  HUGO_VERSION = "0.64.1"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.64.1"
  
  [[redirects]]
  from = "/rightnow"
  to = "http://rightnow.org/Account/Invite/bborm"