[context.production.environment]
  HUGO_VERSION = "0.55.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.55.0"
  
  [[redirects]]
  from = "/rightnow"
  to = "http://rightnow.org/Account/Invite/bborm"