[context.production.environment]
  HUGO_VERSION = "0.64.1"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.64.1"
  
  [[redirects]]
  from = "/rightnow"
  to = "http://rightnow.org/Account/Invite/bborm"

  [[plugins]]
  package = "netlify-plugin-algolia-index"
    [plugins.inputs]
      exclude = ['/admin', '/404.html', '/calendar', '/building-fund', '/posts', '/roku', '/tools', '/tags', '/series', '/index.html', 'googledb52351f8e4eb04e.html','/preachers']